# Generated by Django 4.1 on 2022-08-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullurl', models.CharField(max_length=255)),
                ('shortened', models.CharField(max_length=10)),
            ],
        ),
    ]
